export function changePageColor() {
  document.querySelector('.body').classList.toggle('body_theme_dark')
  document.querySelector('.page').classList.toggle('page_theme_dark')
  document.querySelector('.header__popup').classList.toggle('header__popup_theme_dark')
  document.querySelector('.header__radio').classList.toggle('header__radio_theme_dark')
  document.querySelector('.info__title').classList.toggle('info__title_theme_dark')
  document.querySelector('.info__description').classList.toggle('info__description_theme_dark')
  document.querySelector('.info__text').classList.toggle('info__text_theme_dark')
  document.querySelector('.author__title').classList.toggle('author__title_theme_dark')
  document.querySelector('.author__subtitle').classList.toggle('author__subtitle_theme_dark')
  document.querySelector('.author__text').classList.toggle('author__text_theme_dark')
  document.querySelector('.bikes__title').classList.toggle('bikes__title_theme_dark')
  document.querySelector('.bikes__select').classList.toggle('bikes__select_theme_dark')
  document.querySelector('.workout__title').classList.toggle('workout__title_theme_dark')
  document.querySelector('.workout__subtitle').classList.toggle('workout__subtitle_theme_dark')
  document.querySelector('.footer').classList.toggle('footer_theme_dark')
  document.querySelector('.footer__title').classList.toggle('footer__title_theme_dark')
  document.querySelector('.footer__input').classList.toggle('footer__input_theme_dark')
  document.querySelector('.footer__ok').classList.toggle('footer__ok_theme_dark')
  document.querySelector('.footer__radio').classList.toggle('footer__radio_theme_dark')

  document.querySelectorAll('.header__link').forEach(item => item.classList.toggle('header__link_theme_dark'))
  document.querySelectorAll('.header__burger-link').forEach(item => item.classList.toggle('header__burger-link_theme_dark'))
  document.querySelectorAll('.header__popup-link').forEach(item => item.classList.toggle('header__popup-link_theme_dark'))
  document.querySelectorAll('.bikes__link').forEach(item => item.classList.toggle('bikes__link_theme_dark'))
  document.querySelectorAll('.bikes__description').forEach(item => item.classList.toggle('bikes__description_theme_dark'))
  document.querySelectorAll('.workout__link').forEach(item => item.classList.toggle('workout__link_theme_dark'))
  document.querySelectorAll('.coating__title').forEach(item => item.classList.toggle('coating__title_theme_dark'))
  document.querySelectorAll('.coating__subtitle').forEach(item => item.classList.toggle('coating__subtitle_theme_dark'))
}
